######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 5 19:28:09 2017
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    CryptoVals.h
SOURCES += main.cpp \
    CryptoVals.cpp
QT += network
QT += widgets
QT += core

